1 add eslint rules and prettier for server
celikmurat1845/weekend-blog pull request #4
Opened 2023-09-22 12:48 UTC by celikmurat1845

Closes #1 
- add eslint configuration files
- add prettier configuration files

2023-09-22 21:32 UTC, metehancelik approved these changes

2023-09-22 23:08 UTC, metehancelik requested changes
add npm scripts

2023-09-23 08:38 UTC, demirtasdurmus requested changes

2023-09-23 08:38 UTC, demirtasdurmus commented on apps/server/package.json
> +    "eslint-config-standard-with-typescript": "^39.0.0",
@celikmurat1845, it seems you are not using plugins at line 20,21,22,23. I am confused, if you want to use them you should add them to your config file, else please remove them.

2023-09-23 08:38 UTC, demirtasdurmus commented on apps/server/package.json
> +    "@typescript-eslint/eslint-plugin": "^6.7.0",
And please add npm script to lint in your scripts, then we can have a chance to check if linting rules really does work.

2023-09-23 09:55 UTC, demirtasdurmus commented on apps/server/.eslintrc.json
> +    "node": true
test

2023-09-23 10:05 UTC, demirtasdurmus approved these changes

2023-09-23 10:15 UTC, metehancelik approved these changes

2023-09-23 10:29 UTC, merged